In [9]:
import polars as pl

In [10]:
pymon = pl.read_parquet('./data/raw/pymon.parquet')
pymon.head(5)

shape: (5, 10)
┌────────────┬───────────┬───────────┬─────┬───┬────────────┬────────────┬──────────┬─────────┐
│ id         ┆ name      ┆ type      ┆ hp  ┆ … ┆ attack1_id ┆ attack2_id ┆ weakness ┆ retreat │
│ ---        ┆ ---       ┆ ---       ┆ --- ┆   ┆ ---        ┆ ---        ┆ ---      ┆ ---     │
│ i64        ┆ str       ┆ str       ┆ i64 ┆   ┆ i64        ┆ i64        ┆ str      ┆ i64     │
╞════════════╪═══════════╪═══════════╪═════╪═══╪════════════╪════════════╪══════════╪═════════╡
│ 2288300748 ┆ porygon-z ┆ colorless ┆ 130 ┆ … ┆ 2719601647 ┆ null       ┆ fighting ┆ 1       │
│ 102090707  ┆ alcremie  ┆ psychic   ┆ 80  ┆ … ┆ 1631297795 ┆ null       ┆ metal    ┆ 1       │
│ 3131391599 ┆ klang     ┆ metal     ┆ 80  ┆ … ┆ 344783571  ┆ null       ┆ fire     ┆ 2       │
│ 2368626895 ┆ delibird  ┆ water     ┆ 80  ┆ … ┆ 1159690044 ┆ null       ┆ metal    ┆ 1       │
│ 4191197272 ┆ vanillite ┆ water     ┆ 60  ┆ … ┆ 4023952579 ┆ null       ┆ metal    ┆ 1       │
└────────────┴───────────┴───────────┴─────┴───┴────────────┴────────────┴──────────┴─────────┘

In [14]:
(
    pymon.filter(pl.col('id') == 680619288)
)

shape: (1, 10)
┌───────────┬──────────────────┬───────┬─────┬───┬────────────┬────────────┬──────────┬─────────┐
│ id        ┆ name             ┆ type  ┆ hp  ┆ … ┆ attack1_id ┆ attack2_id ┆ weakness ┆ retreat │
│ ---       ┆ ---              ┆ ---   ┆ --- ┆   ┆ ---        ┆ ---        ┆ ---      ┆ ---     │
│ i64       ┆ str              ┆ str   ┆ i64 ┆   ┆ i64        ┆ i64        ┆ str      ┆ i64     │
╞═══════════╪══════════════════╪═══════╪═════╪═══╪════════════╪════════════╪══════════╪═════════╡
│ 680619288 ┆ mega venusaur ex ┆ grass ┆ 240 ┆ … ┆ 350502607  ┆ null       ┆ fire     ┆ 4       │
└───────────┴──────────────────┴───────┴─────┴───┴────────────┴────────────┴──────────┴─────────┘

In [12]:
pymon.sort('hp', descending=True)

shape: (1_648, 10)
┌────────────┬───────────────┬───────────┬─────┬───┬────────────┬────────────┬───────────┬─────────┐
│ id         ┆ name          ┆ type      ┆ hp  ┆ … ┆ attack1_id ┆ attack2_id ┆ weakness  ┆ retreat │
│ ---        ┆ ---           ┆ ---       ┆ --- ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---     │
│ i64        ┆ str           ┆ str       ┆ i64 ┆   ┆ i64        ┆ i64        ┆ str       ┆ i64     │
╞════════════╪═══════════════╪═══════════╪═════╪═══╪════════════╪════════════╪═══════════╪═════════╡
│ 680619288  ┆ mega venusaur ┆ grass     ┆ 240 ┆ … ┆ 350502607  ┆ null       ┆ fire      ┆ 4       │
│            ┆ ex            ┆           ┆     ┆   ┆            ┆            ┆           ┆         │
│ 1806580470 ┆ mega swampert ┆ water     ┆ 230 ┆ … ┆ 16504392   ┆ null       ┆ lightning ┆ 3       │
│            ┆ ex            ┆           ┆     ┆   ┆            ┆            ┆           ┆         │
│ 2649282092 ┆ mega          ┆ water     ┆ 230 ┆ … ┆ 1977674246 ┆ null       ┆ lightning ┆ 3       │
│            ┆ blastoise ex  ┆           ┆     ┆   ┆            ┆            ┆           ┆         │
│ 422174851  ┆ mega          ┆ fire      ┆ 220 ┆ … ┆ 1633355402 ┆ null       ┆ water     ┆ 2       │
│            ┆ charizard x   ┆           ┆     ┆   ┆            ┆            ┆           ┆         │
│            ┆ ex            ┆           ┆     ┆   ┆            ┆            ┆           ┆         │
│ 1231800017 ┆ mega steelix  ┆ metal     ┆ 220 ┆ … ┆ 37351517   ┆ null       ┆ fire      ┆ 4       │
│            ┆ ex            ┆           ┆     ┆   ┆            ┆            ┆           ┆         │
│ …          ┆ …             ┆ …         ┆ …   ┆ … ┆ …          ┆ …          ┆ …         ┆ …       │
│ 3984380566 ┆ joltik        ┆ lightning ┆ 30  ┆ … ┆ 3199819122 ┆ null       ┆ fighting  ┆ 0       │
│ 2491985984 ┆ tynamo        ┆ lightning ┆ 30  ┆ … ┆ 3779507132 ┆ null       ┆ fighting  ┆ 1       │
│ 445051303  ┆ magikarp      ┆ water     ┆ 30  ┆ … ┆ 898200373  ┆ null       ┆ lightning ┆ 1       │
│ 3616986907 ┆ chingling     ┆ psychic   ┆ 30  ┆ … ┆ 1648738776 ┆ null       ┆ none      ┆ 0       │
│ 619199247  ┆ igglybuff     ┆ colorless ┆ 30  ┆ … ┆ 2188817507 ┆ null       ┆ none      ┆ 0       │
└────────────┴───────────────┴───────────┴─────┴───┴────────────┴────────────┴───────────┴─────────┘

In [15]:
pymon_v = pl.read_parquet("./data/encoded/pymon.vectors.parquet")
pymon.head(5)

shape: (5, 10)
┌────────────┬───────────┬───────────┬─────┬───┬────────────┬────────────┬──────────┬─────────┐
│ id         ┆ name      ┆ type      ┆ hp  ┆ … ┆ attack1_id ┆ attack2_id ┆ weakness ┆ retreat │
│ ---        ┆ ---       ┆ ---       ┆ --- ┆   ┆ ---        ┆ ---        ┆ ---      ┆ ---     │
│ i64        ┆ str       ┆ str       ┆ i64 ┆   ┆ i64        ┆ i64        ┆ str      ┆ i64     │
╞════════════╪═══════════╪═══════════╪═════╪═══╪════════════╪════════════╪══════════╪═════════╡
│ 2288300748 ┆ porygon-z ┆ colorless ┆ 130 ┆ … ┆ 2719601647 ┆ null       ┆ fighting ┆ 1       │
│ 102090707  ┆ alcremie  ┆ psychic   ┆ 80  ┆ … ┆ 1631297795 ┆ null       ┆ metal    ┆ 1       │
│ 3131391599 ┆ klang     ┆ metal     ┆ 80  ┆ … ┆ 344783571  ┆ null       ┆ fire     ┆ 2       │
│ 2368626895 ┆ delibird  ┆ water     ┆ 80  ┆ … ┆ 1159690044 ┆ null       ┆ metal    ┆ 1       │
│ 4191197272 ┆ vanillite ┆ water     ┆ 60  ┆ … ┆ 4023952579 ┆ null       ┆ metal    ┆ 1       │
└────────────┴───────────┴───────────┴─────┴───┴────────────┴────────────┴──────────┴─────────┘

In [18]:
errors = 0
for row in pymon_v.iter_rows():
    id = row[0]
    sel = pymon.filter(pl.col('id') == id)
    count = sel['id'].count()

    if count == 0:
        errors += 1
        print(f"Id {id} has no matches (out of bounds?)")
    
    if count > 1:
        errors += 1
        print(f"Id (id) has {count} collisions (1 expected)")

if errors == 0:
    print("All tests passed, no collisions or failures")

All tests passed, no collisions or failures